# Generated by Django 3.0.8 on 2021-05-14 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pcapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='code',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='referred_by',
        ),
    ]
